// Generated by Rcpp::compileAttributes() - do not edit by hand
// Generator token: 0x6486D5C3

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bnb_singlecp_constant_cpp
List bnb_singlecp_constant_cpp(NumericVector x1, NumericVector x2, double kappa_const);
RcppExport SEXP _bivnegbincp_bnb_singlecp_constant_cpp(SEXP x1SEXP, SEXP x2SEXP, SEXP kappa_constSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_const(kappa_constSEXP);
    rcpp_result_gen = Rcpp::wrap(bnb_singlecp_constant_cpp(x1, x2, kappa_const));
    return rcpp_result_gen;
END_RCPP
}
// bnb_singlecp_dirichlet_cpp
List bnb_singlecp_dirichlet_cpp(NumericVector x1, NumericVector x2, double v1, double v2, double v3, double kappa_const);
RcppExport SEXP _bivnegbincp_bnb_singlecp_dirichlet_cpp(SEXP x1SEXP, SEXP x2SEXP, SEXP v1SEXP, SEXP v2SEXP, SEXP v3SEXP, SEXP kappa_constSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< double >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< double >::type v3(v3SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_const(kappa_constSEXP);
    rcpp_result_gen = Rcpp::wrap(bnb_singlecp_dirichlet_cpp(x1, x2, v1, v2, v3, kappa_const));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bivnegbincp_bnb_singlecp_constant_cpp", (DL_FUNC) &_bivnegbincp_bnb_singlecp_constant_cpp, 3},
    {"_bivnegbincp_bnb_singlecp_dirichlet_cpp", (DL_FUNC) &_bivnegbincp_bnb_singlecp_dirichlet_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_bivnegbincp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
