# Generated by Rcpp::compileAttributes() - do not edit by hand

bnb_singlecp_constant_cpp <- function(x1, x2, kappa_const) {
    .Call(`_bivnegbincp_bnb_singlecp_constant_cpp`, x1, x2, kappa_const)
}

bnb_singlecp_dirichlet_cpp <- function(x1, x2, v1, v2, v3, kappa_const) {
    .Call(`_bivnegbincp_bnb_singlecp_dirichlet_cpp`, x1, x2, v1, v2, v3, kappa_const)
}
